variables:
  SOURCE_FOLDER: "src"
  CFLAGS: "-DBBF_VENDOR_PREFIX=\\\"X_IOPSYS_EU_\\\""
  SYSMNGR_VENDOR_CONFIG_FILE: 'y'
  SYSMNGR_MEMORY_STATUS: 'y'
  SYSMNGR_PROCESS_STATUS: 'y'
  SYSMNGR_SUPPORTED_DATA_MODEL: 'y'
  SYSMNGR_FIRMWARE_IMAGE: 'y'
  SYSMNGR_REBOOTS: 'y'
  SYSMNGR_NETWORK_PROPERTIES: 'y'
  SYSMNGR_VENDOR_EXTENSIONS: 'y'
  SYSMNGR_FWBANK_UBUS_SUPPORT: 'y'
  SYSMNGR_TEMPERATURE_STATUS: 'y'

include:
  - project: 'iopsys/gitlab-ci-pipeline'
    file: '/static-code-analysis.yml'
    ref: '1.2'

stages:
    - static_code_analysis

